Repository QEDK/goodbot, pull requests merged in 2020-07, with the labels that each got.

#36 Automatically parse projects from pages and update list dynamically
  bots/parsebot.py
  requirements.txt
  templates/projects.json
Labels: enhancement, needs testing

#39 Ignore .idea for people using JetBrain IDEs
  .gitignore
  requirements.txt
Labels: enhancement

#40 Few housekeeping fixes
  bots/ircbot.py
  requirements.txt
  test.py
Labels: bug

#41 Make goodbot serve project commands
  bots/goodbot.py
  bots/parsebot.py
  config/pages.json
  templates/replies.json
Labels: enhancement
